### PR TITLE
chore: new tree_sitter

### PR DESCRIPTION
**Pull request by Decodetalkers**

### CODE REVIEW

**Comment by Decodetalkers** [comment]
invalid type: map, expected a sequence at line 30 column 18
what is this?

**Comment by ObserverOfTime** [comment]
The tree-sitter field in package.json must be a list.

**Comment by Decodetalkers** [comment]
@ObserverOfTime Emm, can you help review it?

**Comment by Decodetalkers** [comment]
Is unit test way changed? @ObserverOfTime , I have not found the document about the change of unit test

**Comment by Decodetalkers** [comment]
ok, I will merge it ... but I still have not seen the unit test run.. let me merged it now.. I have already test it locally, seems all is fine.. but do nvim now use the latest treesitter @ObserverOfTime

**Review by dundargoc — APPROVED** [review]
I don't really know TS so don't see much reason for me to review this. I'll add an approve.

**Comment by ObserverOfTime** [comment]
Move the corpus under test/

**Pull request merged**
